name: RESThub, your Spring + Backbone.js stack
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
pygments: true
exclude: [package.json, bower.json, node_modules, bower_components, Gemfile, Gemfile.lock, less, Gruntfile.js]
permalink: /news/:year/:month/:day/:title/

spring-stack-version: 2.2.0
spring-stack-javadoc-version: 2.2
spring-version: 4.1.1
spring-docs-version: 4.1.x
spring-data-version: 1.9.0
spring-data-docs-version: 1.9.x
spring-data-jpa-version: 1.7.0
spring-data-jpa-docs-version: 1.7.x
hibernate-version: 4.3.6
hibernate-docs-version: 4.3
bonecp-version: 0.8.0
hikaricp-version: 2.0.1
mongo-db-version: 2.12.3
spring-data-mongodb-version: 1.5.4
spring-data-mongodb-docs-version: 1.5.x
h2-version: 1.4.181
maven-version: 3.0
jackson-version: 2.4.2
model-mapper-version: 0.7.2
async-http-client-version: 1.8.13
hibernate-validator-version: 5.1.2
hibernate-validator-docs-version: 5.1
testng-version: 6.8.8
fest-assert-version: 2.0M10
fest-assert-short-version: 2
mockito-version: 1.9.5
slf4j-version: 1.7.7
logback-version: 1.1.2

backbone-stack-version: 2.1.2
jquery-version: 1.9.1
backbone-version: 1.0.0
underscore-version: 1.4.4
underscore-string-version: 2.3.0
requirejs-version: 2.1.5
handlebars-version: 1.0
bootstrap-version: 2.3.2
backbone-validation-version: 0.8.1
backbone-query-parameters-version: 0.3.0
backbone-datagrid-version: 0.3.2
backbone-paginator-version: 0.7.0
backbone-associations-version: 0.5.1
momentjs-version: 1.7.2

amqp-hessian-version: 1.0.3
router-version: 1.2.0
