name: RESThub, your Spring + Backbone.js stack
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
pygments: true
exclude: [package.json, bower.json, node_modules, bower_components, Gemfile, Gemfile.lock, less, Gruntfile.js]
spring-stack-version: 2.1.4
spring-stack-javadoc-version: 2.1
